function mat2 = tmorepmat(mat1,bitsd,dim)
dims = size(mat1);
rows = prod(dims(1:dim-1));
tabs = prod(dims(dim+1:end));
bits1 = round(log2(dims(dim)));
num1 = pow2(bits1);
mat1 = reshape(mat1,rows,1,num1,tabs);
numd = pow2(bitsd);
mat2 = repmat(mat1,1,numd,1,1);
mat2 = reshape(mat2,rows,[],tabs);
